import Link from "next/link";
import { services, industries, articles } from "@/lib/content";
import { CTA } from "@/components/CTA";
import { AIAssistant } from "@/components/AIAssistant";

export default function Home() {
  return <><section className="hero"><div className="container"><p className="eyebrow">WEB DESIGN + SEO FOR LOCAL BUSINESSES</p><h1>Web Design & SEO That Generates Local Leads</h1><p className="lead">FolseTech provides professional web design, development and local SEO for professional service businesses in Gonzales, Ascension Parish and South Louisiana. We combine modern web development, technical SEO, local search optimization and conversion strategy to help your business get found on Google and turn more visitors into customers.</p><div className="actions"><Link className="button" href="/free-website-audit">Get Your Free Website Growth Plan</Link><Link className="button button-ghost" href="/contact">Request Free Website Audit</Link></div><div className="proof"><div>Get Found</div><div>Build Trust</div><div>Generate Leads</div><div>Local Authority</div></div></div></section>
  <section className="section"><div className="container"><div className="section-head"><p className="eyebrow">ONE GROWTH SYSTEM</p><h2>Design, search, development, and lead generation should reinforce each other.</h2><p className="lead">Most underperforming websites are not missing one magic feature. They have disconnected architecture, content, UX, performance, and measurement.</p></div><div className="framework"><div><span>01</span>SEARCH<br/><small>Intent + architecture</small></div><div><span>02</span>EXPERIENCE<br/><small>Clarity + trust</small></div><div><span>03</span>CONVERSION<br/><small>Offers + actions</small></div><div><span>04</span>AUTOMATION<br/><small>Qualification + routing</small></div><div><span>05</span>GROWTH<br/><small>Measurement + iteration</small></div></div></div></section>
  <section className="section alt"><div className="container"><div className="section-head"><p className="eyebrow">CORE SERVICES</p><h2>Built around the parts of a website that create business value.</h2></div><div className="grid-3">{services.slice(0,6).map(s=><article className="card" key={s.slug}><h3>{s.title}</h3><p>{s.short}</p><Link className="link" href={`/services/${s.slug}`}>Explore {s.title} →</Link></article>)}</div></div></section>
  <section className="section"><div className="container grid-2"><div><p className="eyebrow">SEO-FIRST DEVELOPMENT</p><h2>Search visibility starts before the first component is coded.</h2><p className="lead">We plan crawl paths, page purpose, metadata, internal linking, structured data, performance budgets, and conversion journeys as part of the architecture—not as a checklist added at launch.</p><Link className="button" href="/services/seo-web-design">See Our SEO Web Design Approach</Link></div><AIAssistant /></div></section>
  <section className="section alt"><div className="container"><div className="section-head"><p className="eyebrow">INDUSTRY SOLUTIONS</p><h2>Different buying journeys need different website systems.</h2></div><div className="grid-3">{industries.slice(0,6).map(i=><article className="card" key={i.slug}><h3>{i.title}</h3><p>{i.description}</p><Link className="link" href={`/industries/${i.slug}`}>View strategy →</Link></article>)}</div></div></section>
  <section className="section"><div className="container"><div className="section-head"><p className="eyebrow">HOW WE BUILD</p><h2>Six stages from business context to measurable growth.</h2></div><div className="grid-3">{[["01","Discover","Business model, customers, competitors, goals, and search opportunity."],["02","Strategy","Site architecture, search intent, conversion journeys, and content framework."],["03","Design","Premium UX built around trust, clarity, and action."],["04","Develop","Fast, scalable Next.js with restrained client-side JavaScript."],["05","Optimize","SEO, schema, analytics, accessibility, and performance hardening."],["06","Grow","Content expansion, testing, measurement, and iterative improvements."]].map(([n,t,d])=><div className="card" key={n}><span className="badge">{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
  <section className="section alt"><div className="container"><div className="section-head"><p className="eyebrow">INSIGHTS</p><h2>Build authority with useful, decision-ready content.</h2></div><div className="grid-3">{articles.map(a=><article className="card" key={a.slug}><span className="badge">{a.category}</span><h3>{a.title}</h3><p>{a.excerpt}</p><Link className="link" href={`/insights/${a.slug}`}>Read insight →</Link></article>)}</div></div></section><CTA /></>;
}
